modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/Uraneptus/Sullys-Mod/issues"

[[mods]] #mandatory
modId = "sullysmod" #mandatory
version = "${file.jarVersion}" #mandatory
logoFile = "sullysmod_banner.png" #optional
authors = "Uraneptus, MiteBeMana, KekeCreations" #optional
credits = "Idea & Assets by GoesBySully" #optional
displayURL = "https://github.com/Uraneptus/Sullys-Mod"
displayName = "Sully's Mod" #mandatory
updateJSONURL = "https://api.modrinth.com/updates/sullysmod/forge_updates.json"
description = '''
Sully's Mod aims to add interesting features while still keeping a vanilla feeling. While the mod's main focus is on entities it tries to add features for every type of minecraft player, explorers, builders, redstone engineers and more.'''
displayTest = "MATCH_VERSION"

[[dependencies.sullysmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="(47,]" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.sullysmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sullysmod]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[7.0.0,)"
    ordering = "BEFORE"
    side = "BOTH"

[modproperties.sullysmod]
    catalogueImageIcon = "sullysmod_icon.png"
    configuredBackground = "sullysmod:textures/block/jade_bricks.png"