modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/Uraneptus/Sullys-Mod/issues"

[[mods]] #mandatory
modId = "sullysmod" #mandatory
version = "${file.jarVersion}" #mandatory
logoFile = "sullysmod_banner.png" #optional
authors = "Uraneptus, MiteBeMana" #optional
credits = "Idea & Assets by GoesBySully" #optional
displayURL = "https://github.com/Uraneptus/Sullys-Mod"
displayName = "Sully's Mod" #mandatory
updateJSONURL = "https://api.modrinth.com/updates/sullysmod/forge_updates.json"
description = '''
Sully's Mod aims to add interesting features while still keeping a vanilla feeling.
'''
displayTest = "MATCH_VERSION"

[[dependencies.sullysmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41.1,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.sullysmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sullysmod]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[6.0.1,)"
    ordering = "BEFORE"
    side = "BOTH"

[[dependencies.sullysmod]]
    modId = "geckolib3"
    mandatory = true
    versionRange = "[3.1.6,)"
    ordering = "BEFORE"
    side = "BOTH"

[modproperties.sullysmod]
    catalogueImageIcon = "sullysmod_icon.png"
    configuredBackground = "sullysmod:textures/block/polished_jade_bricks.png"